sudo: false
os: linux
language: node_js
node_js: '10.14'
dist: trusty
cache:
  directories:
    - ~/.nvm
    - ~/.yarn
    - node_modules

before_install:
  - echo -e "[url \"https://$CI_USER_TOKEN@github.mpi-internal.com\"]\n  insteadOf = ssh://git@github.mpi-internal.com" >> ~/.gitconfig

install:
  - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
  - git fetch origin master
  - yarn --frozen-lockfile

after_success:
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash ./scripts/bump_vuepress.sh; fi
  - bash ./scripts/bump_vuepress.sh
